### ISSUE TITLE
When downloading, fragments are sometimes incorrectly 2 bytes long after processing for no apparent reason.

### ISSUE THREAD

**Issue by DavidBerdik** [DavidBerdik/InfiniDrive#17]
When downloading, fragments are sometimes incorrectly 2 bytes long after processing for no apparent reason. This of course causes the resulting output file to be corrupted. Oddly, this behavior is not consistent. Trying to reproduce the bug results in either one of two scenarios:

- The bug does not occur at all and the file is downloaded properly
- The bug occurs, but not in the same place as in previous tests

**Comment by DavidBerdik** [comment]
Probable source of bug: Google Drive has a bug that sometimes causes images in Docs to not get converted properly, and instead, the image is replaced with a 1x1 image. When this happens, the image that is retrieved from the Word document will have three bytes which, after InfiniDrive removes what is supposed to be the spacer byte, will leave us with 2 bytes.

A simple solution to this problem would be to check that the list of bytes generated from the image does not have a length of 3 before processing and writing to the document. If it does have a length of 3, the Doc should be refetched from Drive.

**Comment by DavidBerdik** [comment]
This issue should be fixed by 6ae15cb460ca4abc106ffd226983d9a66f987311. This issue will be reopened if necessary.

**Comment by innowebka** [comment]
why this error happens when downloading ?
and i cant solve the problemhel me!
python Infinidrive.py download FILEID C:\users\USERNAME\desktop\InfiniDrive-master

Traceback (most recent call last):
  File "Infinidrive.py", line 157, in <module>
    result = open(str(sys.argv[3]), "wb")
PermissionError: [Errno 13] Permission denied: 'C:\\users\\USERNMAE\\desktop\\InfiniDrive-master'

i cant download files but uploading works great.

**Comment by DavidBerdik** [comment]
@innowebka You are probably receiving this error because you are not specifying a full file path. Instead, you are only specifying the directory to which you wish to download.

If you wish to use the download command to save a text file with the name `example.txt`, here is how the command you listed above should be formatted.

```
python InfiniDrive.py download FILEID C:\users\USERNAME\desktop\InfiniDrive-master\example.txt
```

**Comment by innowebka** [comment]
**Thanks** ❤️

**Comment by DavidBerdik** [comment]
> **Thanks** ❤️

You're welcome!
