### ISSUE TITLE
Add Deletion Verification

### ISSUE THREAD

**Issue by DavidBerdik** [DavidBerdik/InfiniDrive#22]
It is currently way too easy to accidentally delete the wrong file. A deletion verification step should be added to fix this. As part of this change, a "force delete" flag should be added to the delete command so that if the user desires, the verification may be bypassed.

**Comment by DavidBerdik** [comment]
This feature was added in f4acce2b9c4932e798507cb38415513e4ac941e8.

**Comment by innowebka** [comment]
this error happened in windows cmd 
i don't know its a bug or not.
deleted a file and again requested to delete the same file again with file id

it gives me this error 

<HttpError 404 when requesting https://www.googleapis.com/drive/v3/files/1XXXXXXXXXXXXXX? returned "File not found: FILE ID 1XXXXXXXXXXXXXXXXX .">
<HttpError 404 when requesting https://www.googleapis.com/drive/v3/files/1XXXXXXXXXXXXXX? returned "File not found: FILE ID 1XXXXXXXXXXXXXXXXX .">
<HttpError 404 when requesting https://www.googleapis.com/drive/v3/files/1XXXXXXXXXXXXXX? returned "File not found: FILE ID 1XXXXXXXXXXXXXXXXX .">

not stops gives the error again and again. sorry for my bad English.

if you don't understand
1.upload a small txt file
2.copy the file id 
3.delete the uploaded txt file it 
4.after the delete request again to delete the same txt file with txt file id

it goes crazy and not stops simply by saying file not found
