### ISSUE TITLE
is there anyway to upload files from url (remote upload ) ?

### ISSUE THREAD

**Issue by innowebka** [DavidBerdik/InfiniDrive#24]
can i upload from url or can you add this feature?

**Comment by DavidBerdik** [comment]
There is no support for uploading files from a URL, but I see no reason why this feature cannot be added in the future.

**Comment by DavidBerdik** [comment]
This feature has been added as of the release of v1.0.9. - https://github.com/DavidBerdik/InfiniDrive/releases/tag/v1.0.9

Here is an example of how to use this feature to upload an Ubuntu ISO directly from one of the official download mirrors and save it with the name "Ubuntu.iso."

```
python InfiniDrive.py upload http://mirror.bytemark.co.uk/ubuntu-releases/18.04.3/ubuntu-18.04.3-desktop-amd64.iso Ubuntu.iso
```

**Comment by innowebka** [comment]
Remote feature works and thanks for your hard work. Tried uploading a file around 5gb in size it works and i will give you more results but now testing max upload file size.

**Comment by DavidBerdik** [comment]
@innowebka You're welcome! As for the file size, you should be able to upload any file regardless of size.

**Comment by innowebka** [comment]
if i upload a 5gb file does it need 5gb internet ?

**Comment by DavidBerdik** [comment]
@innowebka Unfortunately, because of how InfiniDrive works, having faster internet speeds will not dramatically decrease upload times.

**Comment by innowebka** [comment]
i have 5gb internet pack and if i download a file around 5gb my internet pack expires and i cant use internet after downloading 5gb file.
so if i upload 5gb remote file from direct download link (ex: https://website.com/5gbfile.iso) do i need 5gb internet or page load MB is enough ?

**Comment by innowebka** [comment]
no speed per second. i mean internet usage when i do remote upload do i need 5gb internet pack for 5gb remote file ?

**Comment by DavidBerdik** [comment]
Oh, I understand now. Unfortunately, if you are uploading from a direct download link, you will need twice as much data as the file size. This is because when processing direct links, the file is downloaded from the server one chunk at a time, processed, and uploaded to Google Drive. Sadly, there is really no way of working around this.
