### ISSUE TITLE
can't track the uploading progress

### ISSUE THREAD

**Issue by tahadouhi** [DavidBerdik/InfiniDrive#26]
Python : 3.8
Os: Windows 10
Description of the issue : 
the program works well, but I can't track the status of the upload the progress-bar is stuck as in this picture, so i've to wait untill the upload finishes without knowing when it will finish.
![Capture](https://user-images.githubusercontent.com/10810222/76230327-d5e2a800-6223-11ea-98e8-ea224c9fa2d4.JPG)

thank you so much brother !

**Comment by DavidBerdik** [comment]
Hello @tahadouhi,

When you request to upload a file, InfiniDrive does so by breaking the file in to chunks. The progress bar is designed to advance at the start of processing each chunk. When you upload a file that is small enough, there is only 1 chunk, thus, the progress bar immediately jumps to 100%, completes the upload, and InfiniDrive exits. Therefore, this isn't so much a bug as it is perhaps a poor design decision on my part.

If you have any suggestions on how you think the progress bar should operate in the scenario like the one presented above, I am open to them. I agree that as it currently works, it is not exceptionally helpful, but at the same time, I do not have any better ideas for it.

~ David

**Comment by innowebka** [comment]
whats the maximum file upload size ?

**Comment by DavidBerdik** [comment]
@innowebka InfiniDrive does not have a maximum file size! You can throw as large of a file at it as you want!
