### ISSUE TITLE
Upload from url 

### ISSUE THREAD

**Issue by innowebka** [DavidBerdik/InfiniDrive#27]
can i upload from direct url ?
like - https://website.com/name.txt

**Comment by DavidBerdik** [comment]
Hello @innowebka,

Yes, it is possible to upload from a direct URL. You can do that like this:

```
python InfiniDrive.py upload https://website.com/name.txt RemoteText.txt
```

This will store the text file at the address you provided with the name "RemoteText.txt".

For the purposes of keeping the issue tracker clean, I am going to close this. If you have any additional questions however, feel free to reopen it.

~ David

**Comment by innowebka** [comment]
how to change the uploaded file name ?
