### ISSUE TITLE
Add Support for Changing File Names

### ISSUE THREAD

**Issue by DavidBerdik** [DavidBerdik/InfiniDrive#28]
how to change the uploaded file name ?

_Originally posted by @innowebka in https://github.com/DavidBerdik/InfiniDrive/issues/27#issuecomment-599529132_

**Comment by DavidBerdik** [comment]
@innowebka There is currently no support for changing names of uploaded files, but I can add it to a future release.

**Comment by DavidBerdik** [comment]
This feature has been added as of the release of v1.0.12. - https://github.com/DavidBerdik/InfiniDrive/releases/tag/v1.0.12

To rename uploaded files, use the new `rename` command.

**Comment by innowebka** [comment]
rename feature works
