### ISSUE TITLE
Add Support for Detecting Attempts at Deleting Nonexistent Files

### ISSUE THREAD

**Issue by DavidBerdik** [DavidBerdik/InfiniDrive#29]
this error happened in windows cmd 
i don't know its a bug or not.
deleted a file and again requested to delete the same file again with file id

it gives me this error 

<HttpError 404 when requesting https://www.googleapis.com/drive/v3/files/1XXXXXXXXXXXXXX? returned "File not found: FILE ID 1XXXXXXXXXXXXXXXXX .">
<HttpError 404 when requesting https://www.googleapis.com/drive/v3/files/1XXXXXXXXXXXXXX? returned "File not found: FILE ID 1XXXXXXXXXXXXXXXXX .">
<HttpError 404 when requesting https://www.googleapis.com/drive/v3/files/1XXXXXXXXXXXXXX? returned "File not found: FILE ID 1XXXXXXXXXXXXXXXXX .">

not stops gives the error again and again. sorry for my bad English.

if you don't understand
1.upload a small txt file
2.copy the file id 
3.delete the uploaded txt file it 
4.after the delete request again to delete the same txt file with txt file id

it goes crazy and not stops simply by saying file not found

_Originally posted by @innowebka in https://github.com/DavidBerdik/InfiniDrive/issues/22#issuecomment-599748665_

**Comment by DavidBerdik** [comment]
@innowebka This occurs because InfiniDrive does not support detecting attempts to delete nonexistent files. This is a bug and should be fixed in the next release.

**Comment by DavidBerdik** [comment]
This bug has been fixed as of the release of v1.0.12. - https://github.com/DavidBerdik/InfiniDrive/releases/tag/v1.0.12

**Comment by innowebka** [comment]
Uploading...Traceback (most recent call last):
  File "InfiniDrive.py", line 116, in <module>
    fileBytes = infile.read(readChunkSizes)
OSError: [Errno 5] Input/output error


**why this error happens plz help me** ?

**Comment by DavidBerdik** [comment]
@innowebka Could you please share the command you are attempting to use when you get this error?

**Comment by innowebka** [comment]
when uploading file around 6gb

**Comment by DavidBerdik** [comment]
@innowebka Sorry, but could you please post the exact command you are entering?

**Comment by innowebka** [comment]
InfiniDrive.py upload c:\desktop\file.exe filename

**Comment by DavidBerdik** [comment]
@innowebka I think you may mean `c:\Users\<USER ACCOUNT NAME>\desktop\file.exe`

**Comment by innowebka** [comment]
yes thanks and i fixed it. the problem caused by me not the infinidrive problem.

**Comment by innowebka** [comment]
is there any chance that you can add feature that gives us the **size** of each **uploaded files** and **total uploaded volum**e ?
List exceeds 100 files so cant memorize or cant note down each file sizes.

**Comment by DavidBerdik** [comment]
> yes thanks and i fixed it. the problem caused by me not the infinidrive problem.

Excellent! I'm happy to hear it!

> is there any chance that you can add feature that gives us the **size** of each **uploaded files** and **total uploaded volum**e ?
> List exceeds 100 files so cant memorize or cant note down each file sizes.

I am sorry, but I do not understand what you mean. Is this a bug you found?

**Comment by innowebka** [comment]
NO ITS NOT A BUG.

**Comment by DavidBerdik** [comment]
@innowebka Then what is it? I am sorry, but I really do not understand what you are talking about.

**Comment by innowebka** [comment]
noting.

**Comment by DavidBerdik** [comment]
@innowebka I'm sorry. I am just trying to understand what you are referring to. I've noted your request for viewing sizes of files in issue #34, but I am not sure I understand what you meant about the lists.

**Comment by innowebka** [comment]
Uploading... |███░                            | 125/1237An error occurred. Please report this issue on the InfiniDrive GitHub issue tracker and upload your "log.txt" file.
Uploading... |████░                           | 165/1237An error occurred. Please report this issue on the InfiniDrive GitHub issue tracker and upload your "log.txt" file.
Uploading... |██████▓                         | 258/1237An error occurred. Please report this issue on the InfiniDrive GitHub issue tracker and upload your "log.txt" file.
Uploading... |█████████▓                      | 372/1237An error occurred. Please report this issue on the InfiniDrive GitHub issue tracker and upload your "log.txt" file.
Uploading... |██████████▓                     | 414/1237An error occurred. Please report this issue on the InfiniDrive GitHub issue tracker and upload your "log.txt" file.
An error occurred. Please report this issue on the InfiniDrive GitHub issue tracker and upload your "log.txt" file.
Uploading... |███████████                     | 428/1237An error occurred. Please report this issue on the InfiniDrive GitHub issue tracker and upload your "log.txt" file.
Uploading... |███████████▒                    | 443/1237

is this error currupt my file ?

**Comment by DavidBerdik** [comment]
@innowebka In your InfiniDrive directory, there should be a "log.txt" file. Could you please upload it here? There is an known issue with InfiniDrive which is causing data corruption. I believe I have a patch for it that is currently undergoing testing. If successful, it will be pushed in the next release. That said, any data you can provide me will be helpful in resolving the issue.

**Comment by innowebka** [comment]
[log.txt](https://github.com/DavidBerdik/InfiniDrive/files/4447028/log.txt)
am i uploaded the right file ?

**Comment by DavidBerdik** [comment]
@innowebka Yes. This is the correct file. Unfortunately, it looks like you may have used InfiniDrive again after the error occurred, and as a result, your log file was reset and any data that was collected is gone. InfiniDrive v1.0.16 is available on the `v1.0.16` branch if you would like to try out the experimental version that I believe fixes this bug.

If you do not want to try it out, I would encourage you to at least upgrade to v1.0.15. I apologize for the inconvenience that this bug is causing.

**Comment by innowebka** [comment]
do i need to **wait for the patch** or can i **continue to uploading** ? do i need to **stop uploading** ?

**Comment by DavidBerdik** [comment]
@innowebka You can continue to upload, but there is a high risk of your upload becoming corrupted.

This is the version that I believe fixes the bug: https://github.com/DavidBerdik/InfiniDrive/archive/v1.0.16.zip

**Please note however that this release is still in testing.**

**Comment by innowebka** [comment]
Tested with 4GB and 12GB upload and when uploading no error appeared like above mentioned.
so **v.1.0.16 works great**. ❤️

**Comment by DavidBerdik** [comment]
@innowebka Your log.txt file indicates that no corruption occurred! Unfortunately, v1.0.16 does still have a bug that is causing corruption to occur, but a notification will display if this corruption occurs.

**Comment by innowebka** [comment]
how to identify the notification displayed or not ? how notification looks like share a screenshot plz!

**Comment by DavidBerdik** [comment]
@innowebka If your upload becomes corrupted, the following message will appear in the terminal once the upload has completed.

```
InfiniDrive has detected that your upload was corrupted. Please report this issue on the InfiniDrive GitHub issue tracker and upload your "log.txt" file.
```

I am currently testing another patch to v1.0.16 that, if successful, will be released officially. Preliminary results indicate that this patch properly resolves this issue, but until the testing is entirely completed, I cannot be sure.
