### ISSUE TITLE
Add Support for downloading

### ISSUE THREAD

**Issue by innowebka** [DavidBerdik/InfiniDrive#30]
when downloading a file choosing path to save the file (c:\user\folder) sometimes gives me error.
new feature:
if i hit (in windows )
**infinidrive.py download file id** 
its saves straight to downloads folder in ifinidrive-master folder/downloads (ifinidrive-master/downloads)

like in the screenshot

![Screenshot](https://user-images.githubusercontent.com/57298213/76852929-651a3c00-6872-11ea-957f-59a2270efd5a.png)

so there's no need to choose the path

**default feature** : infinidrive.py download file id c:\user\locationtoSave

**new feature** : infinidrive.py download file id 

file straightly goes to downloads folder

**Comment by DavidBerdik** [comment]
I think making the download command not require an explicit value to be given for the final parameter is a good idea, but I have reservations about defaulting to the Downloads directory. Not everyone uses Windows and therefore, I do not think it is a good idea to default to that location. I think the sensible thing to do would be to default to the working directory of InfiniDrive.

**Comment by innowebka** [comment]
default to the working directory of InfiniDrive useful for windows and everyone.
i said InfiniDrive/downloads means downloads folder inside the InfiniDrive Folder not c:\downloads.

**Comment by DavidBerdik** [comment]
Oh, I understand now. Sorry about the confusion. I will consider this, but I still am not sure how I feel about not just having the file saved to the working directory as is currently done. I fear that changing this could confuse users.

**Comment by innowebka** [comment]
now i understand dont add this feature
