### ISSUE TITLE
Add Support for updating Files

### ISSUE THREAD

**Issue by innowebka** [DavidBerdik/InfiniDrive#31]
updating exsiting files

**Comment by DavidBerdik** [comment]
This is a very good idea, but unfortunately, I believe it would require iterating the entire file on Drive, which would effectively mean downloading each file fragment, comparing it to the corresponding fragment of the local file, and uploading the changed fragment if appropriate. That is not to say that there is not value in having this feature, but I want to point out that adding it will not necessarily provide performance gains.

**Comment by DavidBerdik** [comment]
With the introduction of CRC32 validation, adding support for updating files may be more feasible now, as it should no longer be necessary to download each fragment. Instead, we can just check each local fragment of the file against the CRC32 hash of the remote fragment and make changes remotely if necessary.

**Comment by DavidBerdik** [comment]
Support for updating files has been added and will be included as part of the upcoming InfiniDrive v1.0.19 release. Before this update is released, issue #42 should be investigated, as it is very important for supporting the update functionality.
