### ISSUE TITLE
Add support for viewing sizes of uploaded files

### ISSUE THREAD

**Issue by DavidBerdik** [DavidBerdik/InfiniDrive#34]
A command should be added that would allow users to determine the size of an InfiniDrive upload.

**Comment by DavidBerdik** [comment]
Support for viewing sizes of uploaded files was added by 1edaaedfeed0c82410ff8e78f0e305f53ad4a8c7. This feature will be a part of the upcoming InfiniDrive v1.0.19 release.

**Comment by innowebka** [comment]
Thanks again ❤️

**Comment by DavidBerdik** [comment]
@innowebka You're welcome!
