### ISSUE TITLE
bug[maybe] : list command limit

### ISSUE THREAD

**Issue by innowebka** [DavidBerdik/InfiniDrive#36]
when i hit 
**python infinidrive.py list** 
it shows list of 100 files and its id but Ive more than 100 files uploaded to infinidrive.
cant see full list of files uploaded to infinidrive.
tried in cmd and power-shell but end-up in same results.

**Comment by DavidBerdik** [comment]
Hello @innowebka,

Thank you for reporting this. This is indeed a bug.

**Comment by DavidBerdik** [comment]
This bug has been fixed as of the release of v1.0.17.
