### ISSUE TITLE
good wok

### ISSUE THREAD

**Issue by innowebka** [DavidBerdik/InfiniDrive#37]

**Comment by innowebka** [comment]
just delete this issue.

**Comment by DavidBerdik** [comment]
Hello @innowebka,

I'm happy to hear that you got this sorted out on your own! 😊

**Comment by innowebka** [comment]
🥰  😘

**Comment by innowebka** [comment]
God its still a myth you're always active when i open a issue you're ready before me posting an issue.
❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️❤️

**Comment by DavidBerdik** [comment]
Well, I spend way too much time on my computer. Especially now that I cannot go anywhere. 😆
