### ISSUE TITLE
Build User Interface

### ISSUE THREAD

**Issue by DavidBerdik** [DavidBerdik/InfiniDrive#39]
The modular project structure introduced by @maitreerawat's refactoring for the v1.0.18 release should allow for a user interface to built on top of InfiniDrive's existing functionality with relative ease.

**Version control management recommendation:** Since building a user interface component will be more time-consuming than most features that we implement, and we will want to be able to make releases without the UI component being integrated as its development continues, all UI work should be done on a dedicated, non-versioned branch which will receive master branch merges each time an update is released. Once the UI is in a production-ready state, the UI development branch can be merged in to the respective versioned branch.

**Comment by innowebka** [comment]
can i run infinidrive using heroku app ?

**Comment by DavidBerdik** [comment]
@innowebka Yes, you should be able to run InfiniDrive on Heroku. The reason you are receiving this error is because you need to place your credentials.json file in the InfiniDrive root directory.

**Comment by innowebka** [comment]
so its working then can you buit ui in heroku ?

**Comment by DavidBerdik** [comment]
@innowebka The plan is to build a UI that uses libraries that are not platform-dependent. @maitreerawat and I have not researched UI libraries extensively just yet so I cannot comment further on this at the moment. Regarding Heroku, I believe that it is not possible to run program UIs when using it, so you would be limited to using the command line version.

**Comment by AnishDe12020** [comment]
Ok, David, everything works at last but it would be helpful if you could make an application that would create a backup of my whole computer to google drive with this infinidrive thing because I am not paying for extra storage..

**Comment by DavidBerdik** [comment]
@AnishDe12020 If you are looking for an automated way to back up your system with InfiniDrive, your best option would be to use the InfiniDrive FTP server interface feature in conjunction with a program like Rclone.

**Comment by innowebka** [comment]
> 
> 
> @AnishDe12020 If you are looking for an automated way to back up your system with InfiniDrive, your best option would be to use the InfiniDrive FTP server interface feature in conjunction with a program like Rclone.

**how to use infiniDrive FTP ?**

**Comment by DavidBerdik** [comment]
> > @AnishDe12020 If you are looking for an automated way to back up your system with InfiniDrive, your best option would be to use the InfiniDrive FTP server interface feature in conjunction with a program like Rclone.
> 
> **how to use infiniDrive FTP ?**

Use FTP command as documented in the output from running the help command. This will launch a locally hosted FTP server on your computer that you can then log in to using any program that supports FTP.

Here is an example. I have started the InfiniDrive FTP server:

![image](https://user-images.githubusercontent.com/7663225/87257217-449c7000-c467-11ea-91fa-e4476f9619f7.png)

I can then use an FTP client to connect to InfiniDrive. In this example, I am using FileZilla.

![image](https://user-images.githubusercontent.com/7663225/87257253-9fce6280-c467-11ea-946b-9a44ea020dcd.png)

**Comment by AnishDe12020** [comment]
No like I meant uploading folder without zipping them. But now I found a way. I want to just make sure if I can use your code?

**Comment by DavidBerdik** [comment]
> No like I meant uploading folder without zipping them. But now I found a way. I want to just make sure if I can use your code?

You can indeed! InfiniDrive is licensed under GNU General Public License v3.0 (https://github.com/DavidBerdik/InfiniDrive/blob/master/LICENSE) which means you can use InfiniDrive however you like as long as you retain the license, make the source code freely available, state what you changed, and retain credit to the original development team.

**Comment by AnishDe12020** [comment]
Ya it will be opensource in github.

**Comment by DavidBerdik** [comment]
Great! I look forward to checking it out!

**Comment by DavidBerdik** [comment]
Due to upcoming changes to Google Drive's storage quota rules resulting in the end of InfiniDrive development, this issue has been closed without completion.

More information on the changes is available at: https://support.google.com/docs/answer/9312312?hl=en#:~:text=After%20June%201%2C%202021&text=Files%20created%20or%20edited%20in,not%20count%20against%20your%20quota.
