### ISSUE TITLE
Update README with information on end of InfiniDrive development.

### ISSUE THREAD

**Issue by DavidBerdik** [DavidBerdik/InfiniDrive#46]
The project README should be updated with information about the end of InfiniDrive development.

**Comment by innowebka** [comment]
**is this the main reason right?** _https://blog.google/products/photos/storage-policy-update/_

**Comment by DavidBerdik** [comment]
Unfortunately, yes. InfiniDrive will continue to work until this change goes into effect in June of 2021, but I do not see the point in continuing to invest time in developing software that will soon be obsolete, so I am shutting InfiniDrive down. I hate needing to do this, but unfortunately, it's out of my hands. 😔

I will continue exploring new ways to store data, though. 🙂

**Comment by innowebka** [comment]
stored data before June 1 doesn't count the drive storage. so store as much as you want before June 1.

**Comment by DavidBerdik** [comment]
Yes. Uploading will continue to work until June 1, 2021. After that, only downloading will work.

**Comment by DavidBerdik** [comment]
The README has been updated, so this issue will now be closed, making it the final issue to be processed for InfiniDrive.
